version: '3'
services:
 fourlanches-payment-service:
   build:
     context: .
     dockerfile: Dockerfile
   depends_on:
     - mongodb
   environment:
     - MONGO_CONNECTION_STRING=mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@mongodb:27017/${DATABASE_BASE}
   ports:
     - '8080:8080'
 mongodb:
   image: mongo:latest
   environment:
     - MONGO_INITDB_DATABASE=${DATABASE_BASE}
     - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
   ports:
     - '27017:27017'
   volumes:
     - ./data:/data/db